In [4]:
import numpy as np
from numpy.linalg import matrix_power, det, inv


def required_2_matrixes(fun):
    def check(self, *args, **kwargs):

        if self.matrix_2 is None:
            raise ValueError('U need to set secondary matrix')
        return fun(self, *args, **kwargs)
        
    return check


class Matrix:
    def __init__(self, matrix_1, matrix_2=None):
        self.matrix_1 = np.array(matrix_1)
        
        if matrix_2 is None: 
            self.matrix_2 = None 
        else: 
            self.matrix_2 = np.array(matrix_2)
        
    @required_2_matrixes
    def multiply(self):
        return np.multiply(self.matrix_1, self.matrix_2)
    
    @required_2_matrixes
    def divide(self):
        return np.divide(self.matrix_1, self.matrix_2)
    
    @required_2_matrixes
    def add(self):
        return np.add(self.matrix_1, self.matrix_2)
    
    @required_2_matrixes
    def subtract(self):
        return np.subtract(self.matrix_1, self.matrix_2)
        
    def expo(self, power):
        return matrix_power(self.matrix_1, power)
        
    def det(self):
        return det(self.matrix_1)
        
    def inverse(self):
        return inv(self.matrix_1)
        
    def __str__(self):
        return f'{self.matrix_1} \n\n { self.matrix_2 }'

        

    
Calc = Matrix([[1, 2, 3], [0, 1, 2], [2, 1, 1]], [[1, 5, 3], [0, 3, 2], [5, 1, 4]])

print(f'Calc.add() \n { Calc.add() } \n \n \n')

print(f'Calc.multiply() \n { Calc.multiply() } \n \n \n')

print(f'Calc \n { Calc } \n \n \n')

Calc.matrix_2 = None

print(f'Calc.inverse() \n { Calc.inverse() } \n \n \n')

print(f'Calc.det() \n { Calc.det() } \n \n \n')

Calc.add() 
 [[2 7 6]
 [0 4 4]
 [7 2 5]] 
 
 

Calc.multiply() 
 [[ 1 10  9]
 [ 0  3  4]
 [10  1  4]] 
 
 

Calc 
 [[1 2 3]
 [0 1 2]
 [2 1 1]] 

 [[1 5 3]
 [0 3 2]
 [5 1 4]] 
 
 

Calc.inverse() 
 [[-1.  1.  1.]
 [ 4. -5. -2.]
 [-2.  3.  1.]] 
 
 

Calc.det() 
 1.0000000000000002 
 
 

